upstream api {
    server api:8000;
}

upstream mapproxy {
    server mapproxy:8080;
}

server {
    listen 80;
    server_name _;
    client_max_body_size 20m;

    location /mapproxy/ {
        proxy_pass         http://mapproxy/;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   X-Script-Name     /mapproxy;
    }

    location / {
        proxy_pass         http://api;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
}
